### ISSUE TITLE
typeError in container.rb?

### ISSUE THREAD

**Issue by nealrs** [mushishi78/box_packer#2]
I cloned & installed the gem, but I'm having some trouble getting the examples to run. Here's the console output for the first example: 

```
true
2
false
(5,0,0)
/Users/neal/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/box_packer-1.2.1/lib/box_packer/container.rb:58:in `to_s': no implicit conversion of true into String (TypeError)
	from b.rb:14:in `puts'
	from b.rb:14:in `puts'
	from b.rb:14:in `block in <main>'
	from /Users/neal/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/box_packer-1.2.1/lib/box_packer/container.rb:17:in `instance_exec'
	from /Users/neal/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/box_packer-1.2.1/lib/box_packer/container.rb:17:in `initialize'
	from /Users/neal/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/box_packer-1.2.1/lib/box_packer/container.rb:3:in `new'
	from /Users/neal/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/box_packer-1.2.1/lib/box_packer/container.rb:3:in `container'
	from b.rb:3:in `<main>'
```

**Comment by mushishi78** [comment]
Sorry about that. Thanks for reporting it.
